[package]
name = "ferron-passwd"
version = "1.0.0-beta2"
edition = "2021"

[package.metadata.winresource]
ProductName = "Ferron password utility"

[dependencies]
clap = { version = "4.5.28", features = ["derive"] }
password-auth.workspace = true
rpassword = "7.3.1"
yaml-rust2.workspace = true
mimalloc = { workspace = true }

[dev-dependencies]
rusty-hook = { workspace = true }

[build-dependencies]
winresource = "0.1.19"
