[package]
name = "ferron-common"
version = "1.0.0-beta2"
edition = "2021"

[dependencies]
hyper = { workspace = true }
tokio = { workspace = true }
http-body-util = { workspace = true }
yaml-rust2 = { workspace = true }
async-trait = { workspace = true }
pin-project-lite = "0.2.16"
async-channel = { workspace = true }
hyper-tungstenite = { workspace = true }

[dev-dependencies]
rusty-hook = { workspace = true }