name: Run test suite (Ferron 2.x)

on:
  push:
    branches: ["develop-2.x"]
    paths:
      - ".dockerignore"
      - "Cargo.lock"
      - "Cargo.toml"
      - "Dockerfile.test"
      - "dockertest/**"
      - "ferron-docker.kdl"
      - "ferron/**"
      - "ferron-common/**"
      - "ferron-dns-builtin/**"
      - "ferron-load-modules/**"
      - "ferron-modules-builtin/**"
      - "ferron-yaml2kdl-core/**"
      - "ferron-build.yaml"
      - "ferron-build-override.yaml"
      - "wwwroot/**"
      - ".github/workflows/dockertest-v2.yml"
  pull_request:
    branches: ["develop-2.x"]
    paths:
      - ".dockerignore"
      - "Cargo.lock"
      - "Cargo.toml"
      - "Dockerfile.test"
      - "dockertest/**"
      - "ferron-docker.kdl"
      - "ferron/**"
      - "ferron-common/**"
      - "ferron-dns-builtin/**"
      - "ferron-load-modules/**"
      - "ferron-modules-builtin/**"
      - "ferron-yaml2kdl-core/**"
      - "ferron-build.yaml"
      - "ferron-build-override.yaml"
      - "wwwroot/**"
      - ".github/workflows/dockertest-v2.yml"

env:
  CARGO_TERM_COLOR: always

jobs:
  dockertest:
    runs-on: warp-ubuntu-latest-x64-8x

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      # Build the test Ferron image to cache it for the test suite
      - name: Build the test Ferron image
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          file: Dockerfile.test
          load: true
          cache-from: type=gha,url=http://127.0.0.1:49160/,version=1
          cache-to: type=gha,url=http://127.0.0.1:49160/,mode=max,version=1

      # Build the test runner image to cache it for the test suite
      - name: Build the test runner image
        uses: docker/build-push-action@v6.18.0
        with:
          context: ./dockertest/runner
          load: true
          cache-from: type=gha,url=http://127.0.0.1:49160/,version=1
          cache-to: type=gha,url=http://127.0.0.1:49160/,mode=max,version=1

      - name: Run the test suite
        shell: bash
        run: |
          bash ./dockertest/test.sh
